// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using socials.DBContext;

#nullable disable

namespace socials.Migrations.GAR
{
    [DbContext(typeof(GARContext))]
    [Migration("20241125151323_GAR")]
    partial class GAR
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("socials.DBContext.Models.AdressObject", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int?>("Isactive")
                        .HasColumnType("integer")
                        .HasColumnName("isactive");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("Objectguid")
                        .HasColumnType("uuid")
                        .HasColumnName("objectguid");

                    b.Property<long>("Objectid")
                        .HasColumnType("bigint")
                        .HasColumnName("objectid");

                    b.Property<string>("Typename")
                        .HasColumnType("text")
                        .HasColumnName("typename");

                    b.HasKey("Id")
                        .HasName("PK_Addr_Objs");

                    b.ToTable("as_addr_obj", "fias");
                });

            modelBuilder.Entity("socials.DBContext.Models.Hierarchy", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int?>("Isactive")
                        .HasColumnType("integer")
                        .HasColumnName("isactive");

                    b.Property<long>("Objectid")
                        .HasColumnType("bigint")
                        .HasColumnName("objectid");

                    b.Property<long?>("Parentobjid")
                        .HasColumnType("bigint")
                        .HasColumnName("parentobjid");

                    b.HasKey("Id")
                        .HasName("PK_Adm_Hier");

                    b.ToTable("as_adm_hierarchy", "fias");
                });

            modelBuilder.Entity("socials.DBContext.Models.House", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Addnum1")
                        .HasColumnType("text")
                        .HasColumnName("addnum1");

                    b.Property<string>("Addnum2")
                        .HasColumnType("text")
                        .HasColumnName("addnum2");

                    b.Property<int?>("Addtype1")
                        .HasColumnType("integer")
                        .HasColumnName("addtype1");

                    b.Property<int?>("Addtype2")
                        .HasColumnType("integer")
                        .HasColumnName("addtype2");

                    b.Property<string>("Housenum")
                        .HasColumnType("text")
                        .HasColumnName("housenum");

                    b.Property<int?>("Isactive")
                        .HasColumnType("integer")
                        .HasColumnName("isactive");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("Objectguid")
                        .HasColumnType("uuid")
                        .HasColumnName("objectguid");

                    b.Property<long>("Objectid")
                        .HasColumnType("bigint")
                        .HasColumnName("objectid");

                    b.HasKey("Id")
                        .HasName("PK_Houses");

                    b.ToTable("as_houses", "fias");
                });

            modelBuilder.Entity("socials.DBContext.Models.Level", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("levelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objectLevel");

                    b.Property<string>("levelTranslateName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objectLevelText");

                    b.HasKey("Id")
                        .HasName("PK_Level");

                    b.ToTable("as_obj_level", "fias");
                });
#pragma warning restore 612, 618
        }
    }
}
